spring.application.name=Registration

spring.main.banner-mode=off

spring.data.mongodb.uri=mongodb://josephpita24_db_user:%40Elias28Mohere@ac-4ympqel-shard-00-00.ia134by.mongodb.net:27017,ac-4ympqel-shard-00-01.ia134by.mongodb.net:27017,ac-4ympqel-shard-00-02.ia134by.mongodb.net:27017/?ssl=true&replicaSet=atlas-qxrr7c-shard-0&authSource=admin&appName=Cluster0
spring.data.mongodb.database=RegistrationAccount

# Mail settings (replace with your mail server details)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=josephpita24@gmail.com
spring.mail.password=vdvb whvy cwnk brts
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# ===================================================================
# OAuth2 Client Configuration - GitHub
# ===================================================================
# 'github' acts as the registration ID.
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

spring.security.oauth2.client.provider.github.user-name-attribute=login

spring.main.allow-bean-definition-overriding=true


